<?php
/**
 * Section "Deliverables" — SEO House - Web Design.
 * Generated from the approved design by tools/design-import/convert.js.
 * To maintain this file by hand add the tag sh-manual (prefixed with @) as its own line here.
 *
 * @var array $args { f: layout values }
 */
defined( 'ABSPATH' ) || exit;
$f = $args['f'] ?? array();
?>
<section data-screen-label="Deliverables" id="<?= esc_attr(sh_anchor($f, 'pillars')) ?>" style="position: relative; background: var(--sh-surface); color: var(--sh-ink); scroll-margin-top: 88px; border-bottom: 1px solid var(--sh-line);">
    <div style="max-width: 1200px; margin: 0px auto; padding: clamp(34px, 4.4vw, 58px) 20px;">
      <div data-sec-head>
        <?php if (!empty($f['eyebrow'])) : ?><div style="font-size: 13.5px; font-weight: 600; color: var(--sh-link);"><?= esc_html($f['eyebrow'] ?? '') ?></div><?php endif; ?>
        <?php if (!empty($f['title'])) : ?><h2 data-sec-h style="font-family: Alexandria, sans-serif; font-weight: 700; line-height: 1.3;"><?= esc_html($f['title'] ?? '') ?></h2><?php endif; ?>
      </div>
      <?php if (!empty($f['text'])) : ?><p style="font-size: 16px; line-height: 1.85; color: var(--sh-text); margin: 12px 0px 0px; max-width: 46em; text-wrap: pretty;"><?= esc_html($f['text'] ?? '') ?></p><?php endif; ?>
      <div data-wd-grid style="margin-top: clamp(22px, 2.6vw, 32px); display: grid; gap: 16px;">
        <div style="display: flex; flex-direction: column; background: rgb(255, 255, 255); border-radius: 16px; overflow: hidden; box-shadow: 0 14px 34px -28px rgba(6,11,31,.5), 0 0 0 1px var(--sh-line);">
          <div aria-hidden="true" style="padding: 18px 20px; background: linear-gradient(var(--sh-blue-tint), rgb(248, 250, 255)); border-bottom: 1px solid rgba(40, 84, 232, 0.1); height: 132px; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center;"><div style="display: flex; flex-direction: column; align-items: center; gap: 8px;"><span style="width: 44%; height: 16px; border-radius: 5px; background: var(--sh-blue);"></span><span style="display: flex; gap: 8px; width: 100%;"><span style="flex: 1 1 0%; height: 14px; border-radius: 5px; background: rgba(40, 84, 232, 0.25);"></span><span style="flex: 1 1 0%; height: 14px; border-radius: 5px; background: rgba(40, 84, 232, 0.25);"></span><span style="flex: 1 1 0%; height: 14px; border-radius: 5px; background: rgba(40, 84, 232, 0.25);"></span></span><span style="display: flex; gap: 6px; width: 100%;"><span style="flex: 1 1 0%; height: 10px; border-radius: 4px; background: var(--sh-line);"></span><span style="flex: 1 1 0%; height: 10px; border-radius: 4px; background: var(--sh-line);"></span><span style="flex: 1 1 0%; height: 10px; border-radius: 4px; background: var(--sh-line);"></span><span style="flex: 1 1 0%; height: 10px; border-radius: 4px; background: var(--sh-line);"></span></span></div></div>
          <div style="padding: 16px 18px 18px; text-align: center; flex: 1 1 auto;">
            <div style="display: flex; align-items: center; justify-content: center; gap: 9px; color: var(--sh-link);"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="7" height="5" rx="1"></rect><rect x="14" y="3" width="7" height="5" rx="1"></rect><rect x="8.5" y="16" width="7" height="5" rx="1"></rect><path d="M6.5 8v3h11V8M12 11v5"></path></svg><?php if (!empty($f['heading'])) : ?><h3 style="font-family: Alexandria, sans-serif; font-weight: 700; font-size: 17px; margin: 0px; color: var(--sh-ink);"><?= esc_html($f['heading'] ?? '') ?></h3><?php endif; ?></div>
            <?php if (!empty($f['text_2'])) : ?><p style="font-size: 14.5px; line-height: 1.8; color: var(--sh-text); margin: 8px 0px 0px; text-wrap: pretty; max-width: 30em; margin-inline: auto;"><?= esc_html($f['text_2'] ?? '') ?></p><?php endif; ?>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; background: rgb(255, 255, 255); border-radius: 16px; overflow: hidden; box-shadow: 0 14px 34px -28px rgba(6,11,31,.5), 0 0 0 1px var(--sh-line);">
          <div aria-hidden="true" style="padding: 18px 20px; background: linear-gradient(var(--sh-blue-tint), rgb(248, 250, 255)); border-bottom: 1px solid rgba(40, 84, 232, 0.1); height: 132px; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center;"><div style="display: flex; justify-content: center;"><span style="width: 74px; height: 112px; border-radius: 14px; border: 2px solid rgb(6, 11, 31); padding: 8px 7px; display: flex; flex-direction: column; gap: 6px; background: rgb(255, 255, 255);"><span style="height: 8px; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 30px; border-radius: 5px; background: rgba(40, 84, 232, 0.2);"></span><span style="height: 6px; width: 80%; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 6px; width: 60%; border-radius: 3px; background: var(--sh-line);"></span><span style="margin-top: auto; height: 14px; border-radius: 5px; background: var(--sh-blue);"></span></span></div></div>
          <div style="padding: 16px 18px 18px; text-align: center; flex: 1 1 auto;">
            <div style="display: flex; align-items: center; justify-content: center; gap: 9px; color: var(--sh-link);"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="7" y="2" width="10" height="20" rx="2"></rect><path d="M11 18h2"></path></svg><?php if (!empty($f['heading_2'])) : ?><h3 style="font-family: Alexandria, sans-serif; font-weight: 700; font-size: 17px; margin: 0px; color: var(--sh-ink);"><?= esc_html($f['heading_2'] ?? '') ?></h3><?php endif; ?></div>
            <?php if (!empty($f['text_3'])) : ?><p style="font-size: 14.5px; line-height: 1.8; color: var(--sh-text); margin: 8px 0px 0px; text-wrap: pretty; max-width: 30em; margin-inline: auto;"><?= esc_html($f['text_3'] ?? '') ?></p><?php endif; ?>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; background: rgb(255, 255, 255); border-radius: 16px; overflow: hidden; box-shadow: 0 14px 34px -28px rgba(6,11,31,.5), 0 0 0 1px var(--sh-line);">
          <div aria-hidden="true" style="padding: 18px 20px; background: linear-gradient(var(--sh-blue-tint), rgb(248, 250, 255)); border-bottom: 1px solid rgba(40, 84, 232, 0.1); height: 132px; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center;"><div style="display: flex; flex-direction: column; gap: 9px;"><?php $r1_list = $f['items'] ?? []; $i1_n = is_array($r1_list) ? count($r1_list) : 0; foreach ((array) $r1_list as $i1 => $r1) : ?><?php $vt_d2578d96 = ['v1' => ['display: block; width: 82%; height: 100%; background: var(--sh-blue);'], 'v2' => ['display: block; width: 68%; height: 100%; background: var(--sh-blue);'], 'v3' => ['display: block; width: 90%; height: 100%; background: var(--sh-blue);']]; $vk_d2578d96 = $vt_d2578d96[$r1['variant'] ?? 'v1'] ?? $vt_d2578d96['v1']; ?><span style="display: flex; align-items: center; gap: 8px; font-size: 12px; color: var(--sh-text);"><span style="flex: 1 1 0%; height: 8px; border-radius: 99px; background: var(--sh-line); overflow: hidden;"><span style="<?= esc_attr($vk_d2578d96[0] ?? '') ?>"></span></span><?= esc_html($r1['label'] ?? '') ?></span><?php endforeach; ?></div></div>
          <div style="padding: 16px 18px 18px; text-align: center; flex: 1 1 auto;">
            <div style="display: flex; align-items: center; justify-content: center; gap: 9px; color: var(--sh-link);"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 14l4-4"></path><path d="M3.3 16a9 9 0 1 1 17.4 0"></path></svg><?php if (!empty($f['heading_3'])) : ?><h3 style="font-family: Alexandria, sans-serif; font-weight: 700; font-size: 17px; margin: 0px; color: var(--sh-ink);"><?= esc_html($f['heading_3'] ?? '') ?></h3><?php endif; ?></div>
            <?php if (!empty($f['text_4'])) : ?><p style="font-size: 14.5px; line-height: 1.8; color: var(--sh-text); margin: 8px 0px 0px; text-wrap: pretty; max-width: 30em; margin-inline: auto;"><?= esc_html($f['text_4'] ?? '') ?></p><?php endif; ?>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; background: rgb(255, 255, 255); border-radius: 16px; overflow: hidden; box-shadow: 0 14px 34px -28px rgba(6,11,31,.5), 0 0 0 1px var(--sh-line);">
          <div aria-hidden="true" style="padding: 18px 20px; background: linear-gradient(var(--sh-blue-tint), rgb(248, 250, 255)); border-bottom: 1px solid rgba(40, 84, 232, 0.1); height: 132px; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center;"><div style="display: flex; gap: 8px;"><span style="width: 28%; display: flex; flex-direction: column; gap: 6px;"><span style="height: 8px; border-radius: 3px; background: var(--sh-surface);"></span><span style="height: 8px; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 8px; border-radius: 3px; background: rgba(40, 84, 232, 0.35);"></span><span style="height: 8px; border-radius: 3px; background: var(--sh-line);"></span></span><span style="flex: 1 1 0%; border-radius: 6px; border: 1px dashed rgba(40, 84, 232, 0.5); padding: 7px; display: flex; flex-direction: column; gap: 6px;"><span style="height: 9px; width: 70%; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 6px; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 6px; width: 85%; border-radius: 3px; background: var(--sh-line);"></span></span></div></div>
          <div style="padding: 16px 18px 18px; text-align: center; flex: 1 1 auto;">
            <div style="display: flex; align-items: center; justify-content: center; gap: 9px; color: var(--sh-link);"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 20h4L19 9l-4-4L4 16z"></path><path d="M13.5 6.5l4 4"></path></svg><?php if (!empty($f['heading_4'])) : ?><h3 style="font-family: Alexandria, sans-serif; font-weight: 700; font-size: 17px; margin: 0px; color: var(--sh-ink);"><?= esc_html($f['heading_4'] ?? '') ?></h3><?php endif; ?></div>
            <?php if (!empty($f['text_5'])) : ?><p style="font-size: 14.5px; line-height: 1.8; color: var(--sh-text); margin: 8px 0px 0px; text-wrap: pretty; max-width: 30em; margin-inline: auto;"><?= esc_html($f['text_5'] ?? '') ?></p><?php endif; ?>
          </div>
        </div>
        <?php $r1_list = $f['items_2'] ?? []; $i1_n = is_array($r1_list) ? count($r1_list) : 0; foreach ((array) $r1_list as $i1 => $r1) : ?><div style="display: flex; flex-direction: column; background: rgb(255, 255, 255); border-radius: 16px; overflow: hidden; box-shadow: 0 14px 34px -28px rgba(6,11,31,.5), 0 0 0 1px var(--sh-line);">
          <div aria-hidden="true" style="padding: 18px 20px; background: linear-gradient(var(--sh-blue-tint), rgb(248, 250, 255)); border-bottom: 1px solid rgba(40, 84, 232, 0.1); height: 132px; box-sizing: border-box; display: flex; flex-direction: column; justify-content: center;"><div style="<?= esc_attr($i1 === 0 ? 'display: flex; flex-direction: column; gap: 7px;' : 'display: flex; align-items: flex-end; gap: 7px; height: 60px;') ?>"><span style="height: 18px; border-radius: 6px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255);"></span><span style="height: 18px; border-radius: 6px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255);"></span><span style="height: 20px; width: 56%; border-radius: 6px; background: var(--sh-blue);"></span></div></div>
          <div style="padding: 16px 18px 18px; text-align: center; flex: 1 1 auto;">
            <div style="display: flex; align-items: center; justify-content: center; gap: 9px; color: var(--sh-link);"><?= sh_icon($r1['icon'] ?? 'i817572ba') ?><?php if (!empty($r1['heading'])) : ?><h3 style="font-family: Alexandria, sans-serif; font-weight: 700; font-size: 17px; margin: 0px; color: var(--sh-ink);"><?= esc_html($r1['heading'] ?? '') ?></h3><?php endif; ?></div>
            <?php if (!empty($r1['text'])) : ?><p style="font-size: 14.5px; line-height: 1.8; color: var(--sh-text); margin: 8px 0px 0px; text-wrap: pretty; max-width: 30em; margin-inline: auto;"><?= esc_html($r1['text'] ?? '') ?></p><?php endif; ?>
          </div>
        </div><?php endforeach; ?>
      </div>
    </div>
  </section>
