<?php
/**
 * Section "Journey" — SEO House - Online Stores.
 * Generated from the approved design by tools/design-import/convert.js.
 * To maintain this file by hand add the tag sh-manual (prefixed with @) as its own line here.
 *
 * @var array $args { f: layout values }
 */
defined( 'ABSPATH' ) || exit;
$f = $args['f'] ?? array();
?>
<section id="<?= esc_attr(sh_anchor($f, 'journey')) ?>" data-screen-label="Journey" style="position: relative; overflow: hidden; background: var(--sh-bg); scroll-margin-top: 88px; border-bottom: 1px solid var(--sh-line);">
    <div aria-hidden="true" style="position: absolute; inset: 0px; background: radial-gradient(45% 65% at 20% 40%, rgba(40, 84, 232, 0.3), transparent 72%); pointer-events: none;"></div>
    <div style="position: relative; max-width: 1200px; margin: 0px auto; padding: clamp(34px, 4.4vw, 58px) 20px;">
      <div data-sec-head data-sh-center>
        <?php if (!empty($f['eyebrow'])) : ?><div style="font-size: 13.5px; font-weight: 600; color: var(--sh-link);"><?= esc_html($f['eyebrow'] ?? '') ?></div><?php endif; ?>
        <?php if (!empty($f['title'])) : ?><h2 data-sec-h style="font-family: Alexandria, sans-serif; font-weight: 700; line-height: 1.3;"><?= esc_html($f['title'] ?? '') ?></h2><?php endif; ?>
      </div>
      <div data-st-journey style="margin-top: clamp(22px, 2.6vw, 32px); display: grid; gap: clamp(24px, 3vw, 44px); align-items: center;">
        <ol style="list-style: none; margin: 0px; padding: 0px; display: flex; flex-direction: column;">
          <?php $r1_list = $f['items'] ?? []; $i1_n = is_array($r1_list) ? count($r1_list) : 0; foreach ((array) $r1_list as $i1 => $r1) : ?><li style="<?= esc_attr($i1 === 0 ? 'display: flex; gap: 14px; align-items: flex-start; padding: 14px 0px;' : 'display: flex; gap: 14px; align-items: flex-start; padding: 14px 0px; border-top: 1px solid var(--sh-line);') ?>">
            <span style="flex: 0 0 auto; width: 26px; height: 26px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 12.5px; font-weight: 700; display: flex; align-items: center; justify-content: center;"><?= esc_html(($i1 + 1)) ?></span>
            <span style="min-width: 0px;"><?php if (!empty($r1['heading'])) : ?><span style="display: block; font-family: Alexandria, sans-serif; font-weight: 700; font-size: 16.5px; color: var(--sh-ink);"><?= esc_html($r1['heading'] ?? '') ?></span><?php endif; ?><?php if (!empty($r1['label'])) : ?><span style="display: block; font-size: 14.5px; line-height: 1.8; color: var(--sh-ink); margin-top: 4px; text-wrap: pretty;"><?= esc_html($r1['label'] ?? '') ?></span><?php endif; ?></span>
          </li><?php endforeach; ?>
        </ol>
        <div aria-hidden="true" style="border-radius: 16px; background: rgb(251, 252, 255); color: var(--sh-ink); box-shadow: rgba(0, 0, 0, 0.9) 0px 30px 60px -36px; overflow: hidden;">
          <div style="display: flex; align-items: center; gap: 6px; padding: 9px 12px; background: rgb(238, 242, 251); border-bottom: 1px solid var(--sh-line);"><span style="width: 8px; height: 8px; border-radius: 99px; background: var(--sh-line);"></span><span style="width: 8px; height: 8px; border-radius: 99px; background: var(--sh-line);"></span><span style="flex: 1 1 0%; margin-inline-start: 8px; height: 16px; border-radius: 6px; background: rgb(255, 255, 255);"></span></div>
          <div style="padding: 16px; display: grid; gap: 14px;">
            <div style="position: relative; display: flex; flex-wrap: wrap; gap: 6px; align-items: center;"><span aria-hidden="true" style="position: absolute; top: -9px; inset-inline-start: -9px; width: 20px; height: 20px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; box-shadow: rgb(6, 11, 31) 0px 0px 0px 3px;">1</span><?php if (!empty($f['label'])) : ?><span style="flex: 1 1 140px; height: 26px; border-radius: 8px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255); font-size: 11.5px; color: var(--sh-text); display: flex; align-items: center; padding-inline: 10px;"><?= esc_html($f['label'] ?? '') ?></span><?php endif; ?><?php if (!empty($f['label_2'])) : ?><span style="font-size: 11.5px; padding: 5px 10px; border-radius: 99px; background: var(--sh-blue); color: rgb(255, 255, 255);"><?= esc_html($f['label_2'] ?? '') ?></span><?php endif; ?><?php $r1_list = $f['items_2'] ?? []; $i1_n = is_array($r1_list) ? count($r1_list) : 0; foreach ((array) $r1_list as $i1 => $r1) : ?><?php if (!empty($r1['label'])) : ?><span style="font-size: 11.5px; padding: 5px 10px; border-radius: 99px; background: rgba(40, 84, 232, 0.1); color: var(--sh-link);"><?= esc_html($r1['label'] ?? '') ?></span><?php endif; ?><?php endforeach; ?></div>
            <div data-st-mock style="display: grid; gap: 12px;">
              <div style="position: relative; border-radius: 12px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255); padding: 10px; display: flex; gap: 10px;"><span aria-hidden="true" style="position: absolute; top: -9px; inset-inline-start: -9px; width: 20px; height: 20px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; box-shadow: rgb(6, 11, 31) 0px 0px 0px 3px;">2</span><span style="flex: 0 0 72px; height: 72px; border-radius: 9px; background: linear-gradient(135deg, rgb(220, 228, 255), rgb(241, 244, 255));"></span><span style="flex: 1 1 0%; display: flex; flex-direction: column; gap: 6px;"><span style="height: 9px; width: 80%; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 7px; width: 50%; border-radius: 3px; background: var(--sh-line);"></span><span style="display: flex; gap: 4px;"><span style="width: 16px; height: 16px; border-radius: 99px; background: var(--sh-surface);"></span><span style="width: 16px; height: 16px; border-radius: 99px; background: rgb(201, 167, 122);"></span><span style="width: 16px; height: 16px; border-radius: 99px; border: 1px solid rgba(6, 11, 31, 0.2);"></span></span><span style="margin-top: auto; height: 20px; width: 70%; border-radius: 6px; background: var(--sh-blue);"></span></span></div>
              <div style="display: grid; gap: 10px;">
                <div style="position: relative; border-radius: 12px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255); padding: 10px; display: flex; flex-direction: column; gap: 6px;"><span aria-hidden="true" style="position: absolute; top: -9px; inset-inline-start: -9px; width: 20px; height: 20px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; box-shadow: rgb(6, 11, 31) 0px 0px 0px 3px;">3</span><span style="display: flex; justify-content: space-between; font-size: 11px; color: var(--sh-text);"><?php $r1_list = $f['items_3'] ?? []; $i1_n = is_array($r1_list) ? count($r1_list) : 0; foreach ((array) $r1_list as $i1 => $r1) : ?><?php if (!empty($r1['label'])) : ?><span><?= esc_html($r1['label'] ?? '') ?></span><?php endif; ?><?php endforeach; ?></span><span style="height: 7px; border-radius: 3px; background: var(--sh-line);"></span><span style="height: 7px; width: 70%; border-radius: 3px; background: var(--sh-line);"></span></div>
                <div style="position: relative; border-radius: 12px; border: 1px solid var(--sh-line); background: rgb(255, 255, 255); padding: 10px; display: flex; flex-direction: column; gap: 6px;"><span aria-hidden="true" style="position: absolute; top: -9px; inset-inline-start: -9px; width: 20px; height: 20px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; box-shadow: rgb(6, 11, 31) 0px 0px 0px 3px;">4</span><?php if (!empty($f['label_3'])) : ?><span style="font-size: 11px; color: var(--sh-text);"><?= esc_html($f['label_3'] ?? '') ?></span><?php endif; ?><span style="display: flex; gap: 5px;"><span style="flex: 1 1 0%; height: 18px; border-radius: 5px; border: 1px solid rgba(40, 84, 232, 0.5);"></span><span style="flex: 1 1 0%; height: 18px; border-radius: 5px; border: 1px solid var(--sh-line);"></span></span><span style="height: 20px; border-radius: 6px; background: var(--sh-blue);"></span></div>
              </div>
            </div>
            <div style="position: relative; border-radius: 12px; background: var(--sh-surface); padding: 10px 12px; display: flex; align-items: flex-end; gap: 5px; height: 56px;"><span aria-hidden="true" style="position: absolute; top: -9px; inset-inline-start: -9px; width: 20px; height: 20px; border-radius: 999px; background: var(--sh-blue); color: rgb(255, 255, 255); font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; box-shadow: rgb(6, 11, 31) 0px 0px 0px 3px;">5</span><span style="flex: 1 1 0%; height: 30%; border-radius: 3px 3px 0px 0px; background: rgba(40, 84, 232, 0.4);"></span><span style="flex: 1 1 0%; height: 50%; border-radius: 3px 3px 0px 0px; background: rgba(40, 84, 232, 0.5);"></span><span style="flex: 1 1 0%; height: 44%; border-radius: 3px 3px 0px 0px; background: rgba(40, 84, 232, 0.5);"></span><span style="flex: 1 1 0%; height: 70%; border-radius: 3px 3px 0px 0px; background: rgba(40, 84, 232, 0.7);"></span><span style="flex: 1 1 0%; height: 92%; border-radius: 3px 3px 0px 0px; background: var(--sh-blue);"></span></div>
          </div>
        </div>
      </div>
    </div>
  </section>
