<?php
/**
 * Template Name: سيو هاوس — عن الشركة
 * Design source: SEO House - About.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'about' );
get_footer();
