<?php
/**
 * Template Name: سيو هاوس — اتصل بنا
 * Design source: SEO House - Contact.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'contact' );
get_footer();
