<?php
/**
 * Template Name: سيو هاوس — الرئيسية
 * Design source: SEO House - Homepage.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'home' );
get_footer();
