<?php
/**
 * Template Name: سيو هاوس — الأسعار
 * Design source: SEO House - Pricing.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'pricing' );
get_footer();
