<?php
/**
 * Template Name: سيو هاوس — سياسة الخصوصية
 * Design source: SEO House - Privacy Policy.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'privacy-policy' );
get_footer();
