<?php
/**
 * Template Name: سيو هاوس — رفع المنتجات
 * Design source: SEO House - Product Upload.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'products' );
get_footer();
