<?php
/**
 * Template Name: سيو هاوس — قطاع التجارة الإلكترونية
 * Design source: SEO House - Sector Ecommerce.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-ecommerce' );
get_footer();
