<?php
/**
 * Template Name: سيو هاوس — قطاع الأغذية والمطاعم
 * Design source: SEO House - Sector Food.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-food' );
get_footer();
