<?php
/**
 * Template Name: سيو هاوس — قطاع التقنية والبرمجيات
 * Design source: SEO House - Sector Tech.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-tech' );
get_footer();
