<?php
/**
 * Template Name: سيو هاوس — قطاع الصحة والطب
 * Design source: SEO House - Sector Health.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-health' );
get_footer();
