<?php
/**
 * Template Name: سيو هاوس — قطاع التعليم والتدريب
 * Design source: SEO House - Sector Education.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-education' );
get_footer();
