<?php
/**
 * Template Name: سيو هاوس — قطاع القانون والاستشارات
 * Design source: SEO House - Sector Legal.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-legal' );
get_footer();
