<?php
/**
 * Template Name: سيو هاوس — قطاع العقارات والبناء
 * Design source: SEO House - Sector Real Estate.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-real-estate' );
get_footer();
