<?php
/**
 * Template Name: سيو هاوس — القطاعات
 * Design source: SEO House - Sectors.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sectors' );
get_footer();
