<?php
/**
 * Template Name: سيو هاوس — قطاع السياحة والسفر
 * Design source: SEO House - Sector Tourism.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'sector-tourism' );
get_footer();
