<?php
/**
 * Template Name: سيو هاوس — محتوى السيو
 * Design source: SEO House - SEO Content.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo-content' );
get_footer();
