<?php
/**
 * Template Name: سيو هاوس — الاستشارات وتحليل الأداء
 * Design source: SEO House - SEO Consulting.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo-consulting' );
get_footer();
