<?php
/**
 * Template Name: سيو هاوس — السيو الداخلي
 * Design source: SEO House - On-Page SEO.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo-on-page' );
get_footer();
