<?php
/**
 * Template Name: سيو هاوس — السيو التقني
 * Design source: SEO House - Technical SEO.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo-technical' );
get_footer();
