<?php
/**
 * Template Name: سيو هاوس — السيو في السعودية
 * Design source: SEO House - Saudi SEO Page.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo-ksa' );
get_footer();
