<?php
/**
 * Template Name: سيو هاوس — تحسين محركات البحث
 * Design source: SEO House - SEO Service Page.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'seo' );
get_footer();
