<?php
/**
 * Template Name: سيو هاوس — الخدمات
 * Design source: SEO House - All Services.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'services' );
get_footer();
