<?php
/**
 * Template Name: سيو هاوس — ووكومرس
 * Design source: SEO House - WooCommerce.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'stores-woocommerce' );
get_footer();
