<?php
/**
 * Template Name: سيو هاوس — زد
 * Design source: SEO House - Zid.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'stores-zid' );
get_footer();
