<?php
/**
 * Template Name: سيو هاوس — سلة
 * Design source: SEO House - Salla.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'stores-salla' );
get_footer();
