<?php
/**
 * Template Name: سيو هاوس — تصميم المتاجر
 * Design source: SEO House - Online Stores.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'stores' );
get_footer();
