<?php
/**
 * Template Name: سيو هاوس — فريق العمل
 * Design source: SEO House - Team.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'team' );
get_footer();
