<?php
/**
 * Template Name: سيو هاوس — الشروط والأحكام
 * Design source: SEO House - Terms.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'terms' );
get_footer();
