<?php
/**
 * Template Name: سيو هاوس — تأكيد الحجز
 * Design source: SEO House - Thank You.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'thank-you' );
get_footer();
