<?php
/**
 * Template Name: سيو هاوس — رياكت ونكست
 * Design source: SEO House - React Next.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'web-react-next' );
get_footer();
