<?php
/**
 * Template Name: سيو هاوس — البرمجة الخاصة
 * Design source: SEO House - Custom Development.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'web-custom-dev' );
get_footer();
