<?php
/**
 * Template Name: سيو هاوس — ووردبريس
 * Design source: SEO House - WordPress.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'web-wordpress' );
get_footer();
