<?php
/**
 * Template Name: سيو هاوس — تصميم المواقع
 * Design source: SEO House - Web Design.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'web-design' );
get_footer();
