<?php
/**
 * Template Name: سيو هاوس — ويب فلو
 * Design source: SEO House - Webflow.dc.html
 * Generated by tools/design-import/convert.js.
 *
 * @package SEOHouse
 */
defined( 'ABSPATH' ) || exit;
get_header();
sh_render_sections( 'web-webflow' );
get_footer();
